version: '3'
services:
  redmine_dev:
    restart: always
    build: ./redmine/
    container_name: 'redmine_dev'
    ports:
      - 3100:3000
    volumes:
      - ./redmine/datadir:/usr/src/redmine/files
    environment:
      REDMINE_DB_POSTGRES: host.docker.internal
      REDMINE_DB_DATABASE: "${REDMINE_DB_NAME}"
      REDMINE_DB_USERNAME: "${REDMINE_DB_USER}"
      REDMINE_DB_PORT: ${REDMINE_DB_PORT}
      REDMINE_DB_PASSWORD: "${REDMINE_DB_PASS}"
      REDMINE_SECRET_KEY_BASE: "${REDMINE_SECRETKEY}"
    tty: true #正常終了させないための仮プロセス
